# Generated by Django 2.0.8 on 2018-09-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('slug', models.SlugField(max_length=31, unique=True)),
                ('gtfs_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_slug', models.SlugField(max_length=31)),
                ('internal_agency_id', models.IntegerField()),
                ('agency_route_id', models.CharField(max_length=31)),
                ('short_name', models.CharField(max_length=31)),
                ('long_name', models.TextField()),
                ('text_color', models.CharField(max_length=6)),
                ('background_color', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_slug', models.SlugField(max_length=31)),
                ('internal_agency_id', models.IntegerField()),
                ('agency_stop_id', models.CharField(max_length=31)),
                ('stop_name', models.CharField(max_length=63)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_slug', models.SlugField(max_length=31)),
                ('agency_route_id', models.TextField()),
                ('trip_id', models.TextField()),
            ],
        ),
    ]
