# Generated by Django 2.0.8 on 2018-10-19 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('name', models.CharField(max_length=31)),
                ('slug', models.SlugField(max_length=31, primary_key=True, serialize=False)),
                ('time_zone', models.CharField(max_length=31)),
                ('last_update', models.DateTimeField(null=True)),
                ('gtfs_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.TextField()),
                ('monday', models.IntegerField()),
                ('tuesday', models.IntegerField()),
                ('wednesday', models.IntegerField()),
                ('thursday', models.IntegerField()),
                ('friday', models.IntegerField()),
                ('saturday', models.IntegerField()),
                ('sunday', models.IntegerField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcTransitDemo.Agency')),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_agency_id', models.CharField(max_length=15, null=True)),
                ('route_id', models.CharField(max_length=31)),
                ('short_name', models.CharField(max_length=31)),
                ('long_name', models.TextField()),
                ('text_color', models.CharField(max_length=6, null=True)),
                ('background_color', models.CharField(max_length=6, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcTransitDemo.Agency')),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=63)),
                ('stop_name', models.CharField(max_length=63)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcTransitDemo.Agency')),
            ],
        ),
        migrations.CreateModel(
            name='StopTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.TextField()),
                ('stop_id', models.CharField(max_length=63)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcTransitDemo.Agency')),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.TextField()),
                ('service_id', models.TextField()),
                ('trip_id', models.TextField()),
                ('trip_headsign', models.TextField(null=True)),
                ('direction_id', models.IntegerField(null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcTransitDemo.Agency')),
            ],
        ),
    ]
