# Generated by Django 2.0.8 on 2018-09-14 19:30

from django.db import migrations

def add_agencies(apps, schema_editor):
    Agency = apps.get_model('dcTransitDemo', 'Agency')

    Agency(
        name='MTA Maryland',
        slug='mta-md',
        gtfs_link='https://mta.maryland.gov/_googletransit/latest/google_transit.zip'
        ).save()

    Agency(
        name='Virginia Railway Express',
        slug='vre',
        gtfs_link='http://www.vre.org/gtfs/google_transit.zip'
        ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('dcTransitDemo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_agencies)
    ]
