# Generated by Django 2.0.8 on 2018-09-17 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcTransitDemo', '0002_initial_agencies_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='agency_slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcTransitDemo.Agency'),
        ),
        migrations.AlterField(
            model_name='stops',
            name='agency_slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcTransitDemo.Agency'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='agency_slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcTransitDemo.Agency'),
        ),
    ]
