# Generated by Django 2.0.8 on 2018-10-19 00:34

from django.db import migrations
from ..models import Agency, Stops, Routes, Trips, Calendar, StopTimes
from ..staticData.gtfsGeneric import GtfsGeneric
import datetime

import logging

def add_data(apps, schema_editor):
    # Get the MTA MD Agency (only big difference compared to initVreData)
    currentAgency = Agency.objects.get(pk='mta-md')

    # Get a new static parser object with the gtfs link
    staticParser = GtfsGeneric(currentAgency.gtfs_link)

    # Stop list
    stops = staticParser.parseStops()

    # Route list
    routes = staticParser.parseRoutes()

    # Trip list
    trips = staticParser.parseTrips()
	
	# Calendar
    calendar = staticParser.parseCalendar()

    # Stop times list
    stopTimes = staticParser.parseStopTimes()

    # Make the parser object close the zip file
    staticParser.closeZip()

    # Get a logger to display progress in console
    logger = logging.getLogger(__name__)

    # Save the stops
    logger.debug("Saving stops...")
    for stop in stops:
        Stops(
            agency = currentAgency,
            stop_id = stop['stop_id'],
            stop_name = stop['stop_name'],
            lat = stop['stop_lat'],
            lon = stop['stop_lon']
            ).save()

    # Save the routes
    logger.debug("Saving routes...")
    for route in routes:
        Routes(
            agency = currentAgency,
            internal_agency_id = route['internal_agency_id'],
            route_id = route['route_id'],
            short_name = route['short_name'],
            long_name = route['long_name'],
            text_color = route['text_color'],
            background_color = route['background_color']
            ).save()

    # Save the trips
    logger.debug("Saving trips...")
    for trip in trips:
        Trips(
            agency = currentAgency,
            route_id = trip['route_id'],
            service_id = trip['service_id'],
            trip_id = trip['trip_id'],
			trip_headsign = trip['trip_headsign'],
			direction_id = trip['direction_id']
            ).save()
			
	# Save the calendar
    logger.debug("Saving calendar...")
    for item in calendar:
        Calendar(
			agency = currentAgency,
			service_id = item['service_id'],
			monday = item['monday'],
			tuesday = item['tuesday'],
			wednesday = item['wednesday'],
			thursday = item['thursday'],
			friday = item['friday'],
			saturday = item['saturday'],
			sunday = item['sunday']		
			).save()

    # Save the stop times
    logger.debug("Saving stop times, this may take a long time...")
    for stopTime in stopTimes:
        StopTimes(
            agency = currentAgency,
            trip_id = stopTime['trip_id'],
            stop_id = stopTime['stop_id'],
            arrival_time = datetime.time(stopTime['arr_hour'], stopTime['arr_min'], stopTime['arr_sec']),
            departure_time = datetime.time(stopTime['dep_hour'], stopTime['dep_min'], stopTime['dep_sec'])
            ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('dcTransitDemo', '0003_initVreData'),
    ]

    operations = [
        migrations.RunPython(add_data)
    ]
