# Generated by Django 2.0.8 on 2018-09-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcTransitDemo', '0004_remove_stops_internal_agency_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='background_color',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='routes',
            name='text_color',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
