# Generated by Django 2.0.8 on 2018-09-19 21:17

from django.db import migrations
from django.core import serializers
import json
from ..staticData.gtfsGeneric import GtfsGeneric

def add_sample_data(apps, schema_editor):
    Agency = apps.get_model('dcTransitDemo', 'Agency')
    vreJson = serializers.serialize('json', Agency.objects.get(pk='vre'))
    vreDict = json.loads(vreJson)

    staticParser = GtfsGeneric(vreDict['gtfs_link'])

    stops = staticParser.parseStops()
    for stop in stops:
        # put them into database


class Migration(migrations.Migration):

    dependencies = [
        ('dcTransitDemo', '0005_auto_20180917_2041'),
    ]

    operations = [
    ]
