# Generated by Django 2.0.8 on 2018-09-21 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcTransitDemo', '0005_auto_20180917_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.TextField()),
                ('stop_id', models.CharField(max_length=63)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='routes',
            old_name='agency_route_id',
            new_name='route_id',
        ),
        migrations.RenameField(
            model_name='stops',
            old_name='agency_stop_id',
            new_name='stop_id',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='agency_route_id',
            new_name='route_id',
        ),
        migrations.AddField(
            model_name='agency',
            name='last_update',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='time_zone',
            field=models.CharField(default='America/New_York', max_length=31),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stoptimes',
            name='agency_slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcTransitDemo.Agency'),
        ),
    ]
