# Generated by Django 2.0.8 on 2018-09-21 19:40

from django.db import migrations
from ..models import Agency, Stops
from ..staticData.gtfsGeneric import GtfsGeneric

def add_sample_stops_data(apps, schema_editor):
    # Get the VRE agency object
    vre = Agency.objects.get(pk='vre')

    # Get a new static parser object with the gtfs link
    staticParser = GtfsGeneric(vre.gtfs_link)

    # Only ask for stops
    stops = staticParser.parseStops()

    # Make the parser object close the zip file
    staticParser.closeZip()

    # Now loop through and save to database
    for stop in stops:
        Stops(
            agency_slug=vre,
            stop_id=stop['stop_id'],
            stop_name=stop['stop_name'],
            lat=stop['lat'],
            lon=stop['lon']
            ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('dcTransitDemo', '0006_auto_20180921_1939'),
    ]

    operations = [
        migrations.RunPython(add_sample_stops_data)
    ]
