# Generated by Django 2.0.8 on 2018-09-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcTransitDemo', '0007_sampleStopsMigration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
