# Generated by Django 2.0.8 on 2018-09-22 00:48

from django.db import migrations
from ..staticData.gtfsGeneric import GtfsGeneric
from ..models import Agency, StopTimes
import datetime

def add_sample_stop_times_data(apps, schema_editor):
    # Get the VRE agency object
    vre = Agency.objects.get(pk='vre')

    # Get a new static parser object with the gtfs link
    staticParser = GtfsGeneric(vre.gtfs_link)

    # Only ask for stop times
    stopTimes = staticParser.parseStopTimes()

    # Make the parser object close the zip file
    staticParser.closeZip()

    for stopTime in stopTimes:
        StopTimes(
            agency_slug = vre,
            trip_id = stopTime['trip_id'],
            stop_id = stopTime['stop_id'],
            arrival_time = stopTime['arrival_time'],
            departure_time = stopTime['departure_time']
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('dcTransitDemo', '0008_auto_20180922_0045'),
    ]

    operations = [
        migrations.RunPython(add_sample_stop_times_data)
    ]
