# Generated by Django 2.0.8 on 2018-09-22 01:20

from django.db import migrations
from ..staticData.gtfsGeneric import GtfsGeneric
from ..models import Agency, StopTimes
import datetime

def add_mta_md_stop_times(apps, schema_editor):
    # Get the VRE agency object
    vre = Agency.objects.get(pk='mta-md')

    # Get a new static parser object with the gtfs link
    staticParser = GtfsGeneric(vre.gtfs_link)

    # Only ask for stop times
    stopTimes = staticParser.parseStopTimes()

    # Make the parser object close the zip file
    staticParser.closeZip()

    for stopTime in stopTimes:
        StopTimes(
            agency_slug = vre,
            trip_id = stopTime['trip_id'],
            stop_id = stopTime['stop_id'],
            arrival_time = datetime.time(stopTime['arr_hour'], stopTime['arr_min'], stopTime['arr_sec']),
            departure_time = datetime.time(stopTime['dep_hour'], stopTime['dep_min'], stopTime['dep_sec'])
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('dcTransitDemo', '0009_sampleStopTimesMigration'),
    ]

    operations = [
        migrations.RunPython(add_mta_md_stop_times)
    ]
